#!/usr/bin/env bash
# Generates code from the machine-readable ICDs. Generated code is never
# edited by hand.
#
#   systems/icd/sync-link.xml   (ADR-0031, mavgen)   -> sync MCU firmware, ROS car backend
#   systems/icd/can-command.dbc (ADR-0009, cantools) -> sync MCU firmware
#
#   tools/gen-interfaces.sh           regenerate
#   tools/gen-interfaces.sh --check   fail if the committed code is stale (CI)
#
# Needs pymavlink and cantools (both in the dev container).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
work="$(mktemp -d)"
trap 'rm -rf -- "$work"' EXIT

# --- sync link: MAVLink 2 ---------------------------------------------------
# mavgen names the dialect after the file, which must be a C identifier
cp systems/icd/sync-link.xml "$work/arc_sync_link.xml"
python3 -m pymavlink.tools.mavgen --lang=C --wire-protocol=2.0 \
  --output="$work/arc_mavlink" "$work/arc_sync_link.xml" > /dev/null
# mavgen stamps today's date; pin it so the output depends only on the schema
sed -i 's/^#define MAVLINK_BUILD_DATE .*/#define MAVLINK_BUILD_DATE "see systems\/icd\/sync-link.xml"/' \
  "$work/arc_mavlink/arc_sync_link/version.h"

# --- command bus: CAN ------------------------------------------------------
mkdir -p "$work/can_command"
python3 -m cantools generate_c_source --database-name can_command \
  --output-directory "$work/can_command" systems/icd/can-command.dbc > /dev/null
# cantools stamps the time too; keep only its version
sed -i -E 's/(generated by cantools version [0-9.]+) .*\.$/\1./' \
  "$work/can_command/can_command.h" "$work/can_command/can_command.c"

# generated directory -> where it's committed
targets=(
  "arc_mavlink:firmware/sync-mcu/app/generated/arc_mavlink"
  "arc_mavlink:ros/src/arc_backend_car/include/arc_mavlink"
  "can_command:firmware/sync-mcu/app/generated/can_command"
)

stale=0
for t in "${targets[@]}"; do
  src="$work/${t%%:*}" out="${t#*:}"
  if [ "${1:-}" = "--check" ]; then
    if ! diff -r -q "$src" "$out" > /dev/null 2>&1; then
      echo "stale: $out (run tools/gen-interfaces.sh)" >&2
      stale=1
    fi
  else
    rm -rf "$out"
    mkdir -p "$out"
    cp -r "$src/." "$out/"
    echo "generated $out"
  fi
done
exit $stale
