name: Auto Assign Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign Issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: HalfPast9
          numOfAssignee: 1
          allowSelfAssign: true
          abortIfPreviousAssignees: false
          removePreviousAssignees: false
